accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy
from django.views.generic.base import TemplateView

app_name = "accounts"
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard_view'),
    path('my-profile/', views.MyProfileView.as_view(), name="my_profile"),

    path('add-credit-card/', views.AddCreditCardView.as_view(),
         name="add_credit_card"),
    path('payment-details/', views.PaymentDetailsView.as_view(),
         name="payment_details"),
    path('edit-credit-card/<int:pk>/', views.EditCreditCardView.as_view(),
         name="edit_credit_card"),
    path('delete-credit-card/<int:pk>/', views.DeleteCreditCardView.as_view(),
         name="delete_credit_card"),

    path('change-password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('logout/', auth_views.LogoutView.as_view(template_name='landing/logout.html',
                                                  extra_context={'title': 'Logout', }), name="logout"),

    path('user/dashboard/',
         views.UserDashboardView.as_view(), name="user_dashboard"),



    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy(
        'accounts:password_reset_complete')),
        name="password_reset_confirm"),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

gas/urls.py
from django.urls import path
from . import views
app_name = "gas"

urlpatterns = [
    path('new-connection/', views.NewConnectionView.as_view(), name="new_connection"),
    path('view-connection/<int:pk>/', views.DetailConnectionView.as_view(),
         name="view_connection"),
    path('update-connection/<int:pk>/', views.UpdateConnectionView.as_view(),
         name="update_connection"),

    path('user/approved-connection/<int:pk>/', views.ApprovedConnectionView.as_view(),
         name="approved_connection"),

    path('book/cylinder/<int:connection_id>/',
         views.BookingCylinderView.as_view(), name='booking_cylinder'),

    path('booking/list/', views.BookingListView.as_view(), name='booking_list'),

    path('booking/detail/<int:pk>/',
         views.BookingDetailView.as_view(), name='booking_detail')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from gas.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('gas/', include('gas.urls', namespace='gas')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('', HomeView.as_view(), name="home"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

templates/partials/_alert.html
{% if messages %}
    {% for message in messages %}
       <div id="message">
         <div class="alert alert-{{ message.tags }} alert-dismissable text-center m-0" role="alert">
            <button type="button" data-dismiss="alert" class="close"><span aria-hidden=true>
                &times;
            </span></button>
            <strong>
                {% if  message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
                    Error:
                {% else %}
                     {{ message.tags|title }}
                {% endif %}
            </strong>
            {{ message }}
         </div>
       </div>
    {% endfor %}
{% endif %}

templates/partials/_paginate.html
<div class="el-example">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item disabled">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">«</a>
        </li>
        {% else %}
          <li class="page-item disabled">
          <a class="page-link" href="javascript:void(0)">«</a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{i}}</a>
        </li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">»</a>
        </li>
        {% else %}
           <li class="page-item">
          <a class="page-link" href="javascript:void(0)">»</a>
        </li>
        {% endif %}

      </ul>
</div>

templates/partials/_sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'accounts:dashboard_view' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i> {{site_info.site_name}}
        </div>
        <div class="sidebar-brand-text mx-3">
          {{user_profile.get_user_type_display}}
        </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:dashboard_view' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <i class="fas fa-fw fa-cog"></i>
          <span>Connection</span>
        </a>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionSidebar">

          <div class="bg-white py-2 collapse-inner rounded">
            {% if user.user_connection %}
              <a class="collapse-item" href="{% url 'gas:update_connection' user.user_connection.id %}">Edit Connection</a>
              <a class="collapse-item" href="{% url 'gas:approved_connection' user.user_connection.id %}">Go For Booking</a>
            {% else %}
              <a class="collapse-item" href="{% url 'gas:new_connection' %}">New Connection</a>
            {% endif %}

          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Payment</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'accounts:add_credit_card' %}">Add Payment</a>
            <a class="collapse-item" href="{% url 'accounts:payment_details' %}">Payment Details</a>
          </div>
        </div>
      </li>

    <!-- Divider -->
      <hr class="sidebar-divider">

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
          <i class="fas fa-fw fa-cog"></i>
          <span>Booking</span>
        </a>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionSidebar">

          <div class="bg-white py-2 collapse-inner rounded">
            {% if user.user_connection %}
              <a class="collapse-item" href="{% url 'gas:booking_cylinder' user.user_connection.id %}">Book Cylinder</a>
              <a class="collapse-item" href="{% url 'gas:booking_list'%}">All Booking</a>
              <a class="collapse-item" href="{% url 'gas:booking_list'%}?type=confirm">Confirmed Booking</a>
              <a class="collapse-item" href="{% url 'gas:booking_list'%}?type=on_the_way">On The Way Booking</a>
              <a class="collapse-item" href="{% url 'gas:booking_list'%}?type=completed">Completed Booking</a>
            {% else %}
              <a class="collapse-item" href="{% url 'gas:new_connection' %}">New Connection</a>
            {% endif %}

          </div>
        </div>
      </li>




      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">



    </ul>