gas/urls.py
from django.urls import path
from . import views
app_name = "gas"

urlpatterns = [
    path('new-connection/', views.NewConnectionView.as_view(), name="new_connection"),
    path('view-connection/<int:pk>/', views.DetailConnectionView.as_view(),
         name="view_connection"),
    path('update-connection/<int:pk>/', views.UpdateConnectionView.as_view(),
         name="update_connection"),

    path('user/approved-connection/<int:pk>/', views.ApprovedConnectionView.as_view(),
         name="approved_connection"),

    path('book/cylinder/<int:connection_id>/',
         views.BookingCylinderView.as_view(), name='booking_cylinder'),

    path('booking/list/', views.BookingListView.as_view(), name='booking_list'),

    path('booking/detail/<int:pk>/',
         views.BookingDetailView.as_view(), name='booking_detail')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from gas.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('gas/', include('gas.urls', namespace='gas')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('', HomeView.as_view(), name="home"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

gas/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
import random
from django.utils.crypto import get_random_string
import uuid
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


User = get_user_model()


class Staff(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='staff')
    mobile = models.CharField(max_length=20)
    address = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Staff'
        verbose_name_plural = '1. Delivery Staff'

    def __str__(self):
        return self.user.username


def create_new_ref_number():
    return uuid.uuid4().hex[:11].upper()


class Connection(models.Model):
    STATUS_CHOICES = (
        ('1', 'Approved'),
        ('2', 'On Hold'),
        ('3', 'Rejected'),
    )

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='user_connection')
    connection_number = models.CharField(
        max_length=10,
        blank=True,
        editable=False,
        unique=True,
        default=uuid.uuid4
    )
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    mobile = models.CharField(max_length=20)
    gender = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    id_proof = models.ImageField(upload_to='connection')
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='2')

    class Meta:
        verbose_name = 'Connection'
        verbose_name_plural = '2. New Connection'

    def get_absolute_url(self):
        return reverse('gas:view_connection', kwargs={'pk': self.pk})

    def __str__(self):
        return self.connection_number


class GasReffiling(models.Model):
    reffiling_size = models.CharField(max_length=50)
    price = models.FloatField()
    image = models.ImageField(upload_to='gas', null=True, blank=True)

    class Meta:
        verbose_name = 'GasReffiling'
        verbose_name_plural = '3.Gas Reffiling'

    def __str__(self):
        return f"{self.reffiling_size} -->> {self.price}TK"


class Stock(models.Model):
    gas_reffiling = models.ForeignKey(GasReffiling, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = 'Stock'
        verbose_name_plural = '4.Stock'


class Booking(models.Model):
    BOOKING_STATUS = (
        ('1', 'Confirmed'),
        ('2', 'On The Way'),
        ('3', 'Delivered'),
    )

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_bookings')
    connection = models.ForeignKey(Connection, on_delete=models.CASCADE)
    reffiling = models.ForeignKey(GasReffiling, on_delete=models.CASCADE)
    booking_number = models.CharField(
        max_length=10,
        blank=True,
        editable=False,
        unique=True,
        default=uuid.uuid4
    )
    status = models.CharField(
        max_length=10, choices=BOOKING_STATUS, null=True, blank=True)
    staff = models.ForeignKey(
        Staff, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(auto_now_add=True, auto_now=False)

    class Meta:
        verbose_name = 'Booking'
        verbose_name_plural = '5.Booking'

    class Meta:
         permissions = (
             ("can_change_status", "Can Change Status"),
         )

    def __str__(self):
        return self.booking_number


@receiver(post_save, sender=Booking)
def update_stock(sender, instance, created, **kwargs):
    stock_obj = Stock.objects.get(gas_reffiling=instance.reffiling)
    stock_obj.quantity = stock_obj.quantity - 1
    stock_obj.save()


@receiver(post_save, sender=GasReffiling)
def create_stock(sender, instance, created, **kwargs):
    if created:
        stock_obj = Stock.objects.create(gas_reffiling=instance)

templates/connection/approved_connection.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col md-10 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center lead font-weight-bold">{{title}}</h1>
                </div>
                <div class="card-body">
                    <table class="table table-inverse">
                        <thead>
                            <tr>
                                <th>Connection Number</th>
                                <th>Name</th>
                                <th>Mobiel Number</th>
                                <th>Email</th>
                                <th>Address</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for connection in connection_list %}
                                <tr>
                                    <td>{{connection.connection_number}}</td>
                                    <td>{{connection.name}}</td>
                                    <td>{{connection.mobile}}</td>
                                    <td>{{connection.email}}</td>
                                    <td>{{connection.address}}</td>
                                    <td>
                                        <a href="{% url 'gas:view_connection' connection.id %}" class="btn btn-primary btn-block">Book</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/connection/new_connection.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col md-10 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center lead font-weight-bold">{{title}}</h1>
                </div>
                <div class="card-body">
                    <form action="{% url 'gas:new_connection' %}" method="POST" novalidate enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}

                        <button type="submit" class="btn btn-info btn-block">Create Connection</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/connection/update_connection.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col md-10 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center lead font-weight-bold">{{title}}</h1>
                </div>
                <div class="card-body">
                    <form action="{% url 'gas:update_connection' connection.id %}" method="POST" novalidate enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}

                        <button type="submit" class="btn btn-info btn-block">Update Connection</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/connection/view_connection.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col md-10 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center lead font-weight-bold">{{title}}</h1>
                </div>
                <div class="card-body">
                    <table class="table table-inverse">
                       <tbody class="text-center">
                            <tr class="bg-danger text-white font-weight-bold">
                                <td>Connection Number</td>
                                <td>{{connection.connection_number}}</td>
                            </tr>
                            <tr class="bg-success text-white font-weight-bold">
                                <td>Connection Status</td>
                                <td>{{connection.get_status_display}}</td>
                            </tr>
                            <tr class="bg-secondary text-white font-weight-bold">
                                <td>Name</td>
                                <td>{{connection.name}}</td>
                            </tr>
                            <tr class="bg-secondary text-white font-weight-bold">
                                <td>Email</td>
                                <td>{{connection.email}}</td>
                            </tr>
                            <tr class="bg-secondary text-white font-weight-bold">
                                <td>Phone</td>
                                <td>{{connection.mobile}}</td>
                            </tr>
                            <tr class="bg-secondary text-white font-weight-bold">
                                <td>Address</td>
                                <td>{{connection.address}}</td>
                            </tr>
                        </tbody>
                    </table>

                    <a href="{% url 'gas:booking_cylinder' connection.id %}" class="btn btn-block btn-success">Book</a>
                </div>
            </div>


        </div>
    </div>
{% endblock content %}