accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy
from django.views.generic.base import TemplateView

app_name = "accounts"
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard_view'),
    path('my-profile/', views.MyProfileView.as_view(), name="my_profile"),

    path('add-credit-card/', views.AddCreditCardView.as_view(),
         name="add_credit_card"),
    path('payment-details/', views.PaymentDetailsView.as_view(),
         name="payment_details"),
    path('edit-credit-card/<int:pk>/', views.EditCreditCardView.as_view(),
         name="edit_credit_card"),
    path('delete-credit-card/<int:pk>/', views.DeleteCreditCardView.as_view(),
         name="delete_credit_card"),

    path('change-password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('logout/', auth_views.LogoutView.as_view(template_name='landing/logout.html',
                                                  extra_context={'title': 'Logout', }), name="logout"),

    path('user/dashboard/',
         views.UserDashboardView.as_view(), name="user_dashboard"),



    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy(
        'accounts:password_reset_complete')),
        name="password_reset_confirm"),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

gas/urls.py
from django.urls import path
from . import views
app_name = "gas"

urlpatterns = [
    path('new-connection/', views.NewConnectionView.as_view(), name="new_connection"),
    path('view-connection/<int:pk>/', views.DetailConnectionView.as_view(),
         name="view_connection"),
    path('update-connection/<int:pk>/', views.UpdateConnectionView.as_view(),
         name="update_connection"),

    path('user/approved-connection/<int:pk>/', views.ApprovedConnectionView.as_view(),
         name="approved_connection"),

    path('book/cylinder/<int:connection_id>/',
         views.BookingCylinderView.as_view(), name='booking_cylinder'),

    path('booking/list/', views.BookingListView.as_view(), name='booking_list'),

    path('booking/detail/<int:pk>/',
         views.BookingDetailView.as_view(), name='booking_detail')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from gas.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('gas/', include('gas.urls', namespace='gas')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('', HomeView.as_view(), name="home"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

templates/landing/home.html
{% extends "landing_base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
<div class="col-md-12 mt-2">
    <div>
        <p><img id="Img41" title="Leh LPG" src="{% static 'img/Leh.jpg' %}" alt="Leh LPG" width="100%"></p>
    </div>
    <div class="card">
                <div class="crad-header">
                    <h4 class="lead font-weight-bold text-center my-2">{{title}}</h4>

                </div>
                <div class="card-body">

                        <div class="row">
                            {% for cylinder in cylinder_list %}


                                <div class="col-md-4">
                                    <div class="card border-dark p-4">
                                        <img src="{{cylinder.image.url}}" class="figure-img img-fluid rounded">
                                        <h5 class="lead font-weight-bold text-dark text-center">{{cylinder.reffiling_size}}</h5>
                                        <h5 class="lead font-weight-bold text-dark text-center">Price {{cylinder.price}}</h5>

                                        {% if user.is_authenticated and user.user_connection %}
                                            <a href="{% url 'gas:booking_cylinder' user.user_connection.id %}" class="btn btn-primary btn-block">Book</a>
                                        {% else %}
                                            <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-block">Login To Book</a>
                                        {% endif %}

                                    </div>
                                </div>

                            {% endfor %}
                        </div>

                </div>
    </div>
    <div class="col-md-12 d-flex justify-content-center mt-3">
        {% include 'partials/_paginate.html' %}
    </div>
</div>
{% endblock content %}

templates/landing/login.html
{% extends "landing_base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
<div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                        </div>
                        <form class="user" method="POST" action="{% url 'accounts:login' %}" novalidate>
                            {% csrf_token %}
                            {{form|crispy}}
                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                Login
                            </button>

                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="{% url 'accounts:register' %}">Create an Account!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/landing/logout.html
{% extends "landing_base.html" %}

{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <div class="card mt-4">
                            <div class="card-body">
                                <p>
                                    You Have Successfully Loggedout.
                                </p>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div

{% endblock content %}

templates/landing/site_faq.html
{% extends "landing_base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <main class="mt-2">
        <header class="text-center text-dark font-weight-bold border-bottom">
            <h4 class="text-center text-dark font-weight-bold">
                {{title}}
            </h4>
        </header>

        <div class="container mt-5">
            <div class="row">
                <div class="col-md-10 mx-auto mt-3">
                    <div id="accordion" class="mb-3">
                        {% for faq in faq_list %}
                            <div class="card mb-0">
                            <div class="card-header" id="heading{{faq.id}}">
                                <h6 class="m-0">
                                    <a href="#collapse{{faq.id}}" class="text-dark font-weight-bold" data-toggle="collapse"
                                            aria-expanded="true"
                                            aria-controls="collapse{{faq.id}}">
                                        {{faq.question}}
                                    </a>
                                </h6>
                            </div>

                            <div id="collapse{{faq.id}}" class="collapse {% if forloop.counter == 1 %}show{% endif %}" aria-labelledby="heading{{faq.id}}" data-parent="#accordion">
                                <div class="card-body text-dark font-weight-bold">
                                    {{faq.answer}}
                                </div>
                            </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    </main>
{% endblock content %}