accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy
from django.views.generic.base import TemplateView

app_name = "accounts"
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard_view'),
    path('my-profile/', views.MyProfileView.as_view(), name="my_profile"),

    path('add-credit-card/', views.AddCreditCardView.as_view(),
         name="add_credit_card"),
    path('payment-details/', views.PaymentDetailsView.as_view(),
         name="payment_details"),
    path('edit-credit-card/<int:pk>/', views.EditCreditCardView.as_view(),
         name="edit_credit_card"),
    path('delete-credit-card/<int:pk>/', views.DeleteCreditCardView.as_view(),
         name="delete_credit_card"),

    path('change-password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('logout/', auth_views.LogoutView.as_view(template_name='landing/logout.html',
                                                  extra_context={'title': 'Logout', }), name="logout"),

    path('user/dashboard/',
         views.UserDashboardView.as_view(), name="user_dashboard"),



    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy(
        'accounts:password_reset_complete')),
        name="password_reset_confirm"),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

gas/urls.py
from django.urls import path
from . import views
app_name = "gas"

urlpatterns = [
    path('new-connection/', views.NewConnectionView.as_view(), name="new_connection"),
    path('view-connection/<int:pk>/', views.DetailConnectionView.as_view(),
         name="view_connection"),
    path('update-connection/<int:pk>/', views.UpdateConnectionView.as_view(),
         name="update_connection"),

    path('user/approved-connection/<int:pk>/', views.ApprovedConnectionView.as_view(),
         name="approved_connection"),

    path('book/cylinder/<int:connection_id>/',
         views.BookingCylinderView.as_view(), name='booking_cylinder'),

    path('booking/list/', views.BookingListView.as_view(), name='booking_list'),

    path('booking/detail/<int:pk>/',
         views.BookingDetailView.as_view(), name='booking_detail')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from gas.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('gas/', include('gas.urls', namespace='gas')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('', HomeView.as_view(), name="home"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

templates/payment/add_credit_card.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="crad-header">
                    <h4 class="lead font-weight-bold text-center my-2">{{title}}</h4>
                    <div class="form-group text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item"><i class="text-muted fab fa-cc-visa fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-mastercard fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-amex fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-discover fa-3x"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    {{form.errors}}
                    <form action="{% url 'accounts:add_credit_card' %}" method="POST" novalidate>
                        {% csrf_token %}
                        {{form|crispy}}

                        <input type="submit" value="Save" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/payment/delete_credit_card.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col-md-10 mx-auto">
             <div class="card">
                 <div class="card-header">
                     <h5 class="lead text-center font-weight-bold text-dark">{{title}}</h5>
                 </div>
                 <div class="card-body">
                    <form method="post">{% csrf_token %}
                        <p>Are you sure you want to delete "{{ object }}"?</p>
                        <input type="submit" value="Confirm" class="btn btn-danger">
                    </form>
                 </div>
             </div>
        </div>
    </div>
{% endblock content %}

templates/payment/edit_credit_card.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="crad-header">
                    <h4 class="lead font-weight-bold text-center my-2">{{title}}</h4>
                    <div class="form-group text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item"><i class="text-muted fab fa-cc-visa fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-mastercard fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-amex fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-discover fa-3x"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{% url 'accounts:edit_credit_card' user_credit_card.id %}" method="POST" novalidate>
                        {% csrf_token %}
                        {{form|crispy}}

                        <input type="submit" value="Save" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/payment/payment_details.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="crad-header">
                    <h4 class="lead font-weight-bold text-center my-2">{{title}}</h4>
                    <div class="form-group text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item"><i class="text-muted fab fa-cc-visa fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-mastercard fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-amex fa-3x"></i></li>
                            <li class="list-inline-item"><i class="fab fa-cc-discover fa-3x"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-inverse table-hover">
                        <thead>
                            <tr>
                                <th>Folder Name</th>
                                <th>Card Number</th>
                                <th>Expiration</th>
                                <th>Security Code</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user_payment  in user_all_payment %}


                                <tr>
                                    <td>{{user_payment.card_holder}}</td>
                                    <td>{{user_payment.card_number}}</td>
                                    <td>{{user_payment.expiration}}</td>
                                    <td>{{user_payment.security_code|first}} **** {{user_payment.security_code|last}}</td>
                                    <td>
                                        <a href="{% url 'accounts:edit_credit_card' user_payment.id %}" class="btn btn-sm btn-success">Edit</a>--
                                        <a href="{% url 'accounts:delete_credit_card' user_payment.id %}" class="btn btn-sm btn-success">Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}